[package]
name = "exploring-nannou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "bouncing-ball-no-vec"
path = "bouncing-ball-no-vec/main.rs"

[dependencies]
nannou = "0.18.1"
